# .github/workflows/cd.yml

name: CD Pipeline - Build and Push Docker Image

# This workflow runs only when code is pushed to the 'main' branch
on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checks out your repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Logs into Docker Hub using the secrets you stored
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.aks484 }}
          password: ${{ secrets.dckr_pat_yfs0GUkGUR2KvZ9yc3lI0A50Sf4 }}

      # Step 3: Builds the Docker image from your dockerfile and pushes it to your Docker Hub repository
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: aks484/iris-classifier:1.0 # IMPORTANT: Change this line!


          