# .github/workflows/retrain.yml
name: Trigger Model Retraining

on:
  repository_dispatch:
    types: [retrain-model] # This workflow runs when it receives this event type

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . # Install project in editable mode

      - name: Run Training Script
        run: |
          python src/train.py # Or wherever your train.py is located
        

      